apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::083495778532:role/eks-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-05T11:48:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1673"
  uid: c5f72416-f3f1-49d3-9a01-f5d3beee34b4
data:
  mapUsers: |
    - userarn: arn:aws:iam::083495778532:user/Junseo  
      username: admin
      groups:
        - system:masters
